#!/bin/sh

echo "/* -- block generated by $0 */"

for i in $(grep _CLOSE tokens.txt)
do
	echo gap_$(echo $i|sed 's/_CLOSE//'| tr '[:upper:]' '[:lower:]')"		: $i											{ if ( DEBUG_LEVEL != 0 ) printf("'"reduce gaps '$i'\\n"'"); }"
	echo "			| error												{ if ( DEBUG_LEVEL != 0 ) printf("'"reduce gaps '$i' ERROR\\n"'"); errors++; yyerrok; }"
	echo "			;"
	echo
done

echo "/* -- end of block */"
