#!/bin/sh

A=0;
echo "/* -- block generated by $0 */"


for i in $(cat tokens.txt)
do
	if [ $A -eq 0 ]; then
		echo "token		:" $i"								{ if ( DEBUG_LEVEL != 0) printf("'"reduce token '$i'\\n"'"); }"
	else		
		echo "			|" $i"								{ if ( DEBUG_LEVEL != 0) printf("'"reduce token '$i'\\n"'"); }"
	fi
	
	A=1;
done

echo "			| END								{ if ( DEBUG_LEVEL != 0) printf("'"reduce token '$i'\\n"'"); }"
echo "			;"
echo "/* -- end of block */"
